 let CategoriesType = {
    SET_CATEGORIES:'SET_CATEGORIES',
    SET_SELECTED_CATEGORIES:'SET_SELECTED_CATEGORIES',
    SET_SELECTED_SUB_CATEGORIES:'SET_SELECTED_SUB_CATEGORIES',
    SET_CODE:'SET_CODE',
    SET_LAST_CATEGORIES:'SET_LAST_CATEGORIES'
}

export default CategoriesType